/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-wifi_dsss
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_WIFI_DSSS_API_H
#define INCLUDED_WIFI_DSSS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_wifi_dsss_EXPORTS
#define WIFI_DSSS_API __GR_ATTR_EXPORT
#else
#define WIFI_DSSS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_WIFI_DSSS_API_H */
