/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(chip_sync_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(39fb8ecfcedd02e6ce1ffaf7ae15155f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wifi_dsss/chip_sync_c.h>
// pydoc.h is automatically generated in the build directory
#include <chip_sync_c_pydoc.h>

void bind_chip_sync_c(py::module& m)
{

    using chip_sync_c = gr::wifi_dsss::chip_sync_c;


    py::class_<chip_sync_c, gr::block, gr::basic_block, std::shared_ptr<chip_sync_c>>(
        m, "chip_sync_c", D(chip_sync_c))

        .def(py::init(&chip_sync_c::make),
             py::arg("is_long_preamble"),
             py::arg("threshold"),
             D(chip_sync_c, make))

        .def("set_preamble_type",
             &chip_sync_c::set_preamble_type,
             py::arg("is_long_preamble"),
             "Set the preamble type.")
     
        .def("set_threshold",
             &chip_sync_c::set_threshold,
             py::arg("threshold"),
             "Set the threshold for decoding.")

        ;
}
