/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ppdu_prefixer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(91e6821dd5a529b498ba542a470fe2d7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wifi_dsss/ppdu_prefixer.h>
// pydoc.h is automatically generated in the build directory
#include <ppdu_prefixer_pydoc.h>

void bind_ppdu_prefixer(py::module& m)
{

    using ppdu_prefixer = gr::wifi_dsss::ppdu_prefixer;


    py::class_<ppdu_prefixer, gr::block, gr::basic_block, std::shared_ptr<ppdu_prefixer>>(
        m, "ppdu_prefixer", D(ppdu_prefixer))

        .def(py::init(&ppdu_prefixer::make), py::arg("rate"), D(ppdu_prefixer, make))

        .def(
            "update_rate",
            &ppdu_prefixer::update_rate,
            py::arg("rate"),
            "Set the PPDU Rate Dynamically."
        )

        ;
}
