/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ppdu_chip_mapper_bc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(03e18f1c6c5b49812a3cec4b4f12b4b8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wifi_dsss/ppdu_chip_mapper_bc.h>
// pydoc.h is automatically generated in the build directory
#include <ppdu_chip_mapper_bc_pydoc.h>

void bind_ppdu_chip_mapper_bc(py::module& m)
{

    using ppdu_chip_mapper_bc = gr::wifi_dsss::ppdu_chip_mapper_bc;


    py::class_<ppdu_chip_mapper_bc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ppdu_chip_mapper_bc>>(
        m, "ppdu_chip_mapper_bc", D(ppdu_chip_mapper_bc))

        .def(py::init(&ppdu_chip_mapper_bc::make),
             py::arg("lentag"),
             D(ppdu_chip_mapper_bc, make))


        ;
}
